#!/bin/sh /etc/rc.common

START=99

start() {
  . /lib/functions.sh
  
  case $(board_name) in
		hinlink,opc-h69k)
	  if lsmod | grep -q pwm_fan
	  then
	     rmmod pwm_fan
	  fi
      echo 0 > /sys/class/pwm/pwmchip0/export
      echo 40000 > /sys/class/pwm/pwmchip0/pwm0/period
      echo 20000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
      echo normal > /sys/class/pwm/pwmchip0/pwm0/polarity
      echo 1 > /sys/class/pwm/pwmchip0/pwm0/enable
			;;
	esac
}
